# Generated by Django 3.2.13 on 2022-06-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0003_auto_20220623_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='todoItem.tag'),
        ),
    ]
