# Generated by Django 3.2.13 on 2022-06-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0005_alter_todoitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='folder',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='todoItem.folder'),
        ),
    ]
