# Generated by Django 3.2.13 on 2022-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0006_todoitem_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todoItem.Tag'),
        ),
    ]
