# Generated by Django 3.2.13 on 2022-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0010_auto_20220623_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todoItem.Tag'),
        ),
    ]
