# Generated by Django 3.2.13 on 2022-06-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0012_auto_20220624_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='todoItem.folder'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todoItem.Tag'),
        ),
    ]
