# Generated by Django 3.2.13 on 2022-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoItem', '0013_auto_20220624_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='todos', to='todoItem.Tag'),
        ),
    ]
