# Generated by Django 3.2.13 on 2022-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary'), ('rather not to say', 'rather not to say')], default='rather not to say', max_length=50),
        ),
    ]
